googleAnalytics = "G-3CCF1G8NWP"
baseURL = "https://mahdiarsadeghi/github.io/disquisition"
disqusShortname = "dissertation"
disablePathToLower = true
enableGitInfo = true
languageCode = "en-us"
title = "Dissertation"
BookRepo = 'https://github.com/mahdiarsadeghi/disquisition/docs'
BookCommitPath = 'commit'
BookDateFormat = 'Jan 2, 2006'
