name: Makefile CI

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
